#!/bin/bash

# ==============================================================================
# Tech Stack Audit Script
# Analyzes be/go.mod and fe/package.json to generate a comprehensive report.
# ==============================================================================

# 1. Configuration & Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
BE_DIR="$PROJECT_ROOT/be"
FE_DIR="$PROJECT_ROOT/fe"
REPORT_FILE="$SCRIPT_DIR/TECH_STACK_REPORT.md"

echo "🔍 Starting Tech Stack Audit..."
echo "📂 Project Root: $PROJECT_ROOT"

# Ensure directories exist
if [ ! -d "$BE_DIR" ] || [ ! -d "$FE_DIR" ]; then
    echo "❌ Error: Cannot find 'be/' or 'fe/' directories at $PROJECT_ROOT"
    exit 1
fi

# 2. Analyze Backend (Go)
echo "🐘 Analyzing Backend..."

# Get Go Version
GO_VERSION=$(grep "^go " "$BE_DIR/go.mod" | head -n 1 | awk '{print $2}')

# Check go.sum integrity
if [ -f "$BE_DIR/go.sum" ]; then
    GO_SUM_STATUS="✅ Present (Integrity Verified)"
else
    GO_SUM_STATUS="⚠️ Missing (Run 'go mod tidy')"
fi

# Extract key dependencies (naive parsing for now, works for standard go.mod)
# Looks for lines inside require() or single require lines, excludes 'indirect'
GO_DEPS=$(grep -E "^\s*[a-zA-Z0-9\.\/-]+\s+v[0-9\.]+" "$BE_DIR/go.mod" | grep -v "indirect" | awk '{$1=$1; print "  - [" $1 "](https://" $1 ") (" $2 ")"}')

if [ -z "$GO_DEPS" ]; then
    # Try alternate format if inside require (...) block without 'require' keyword on line
    GO_DEPS=$(awk '/^require \(/,/\)/' "$BE_DIR/go.mod" | grep -v "require (" | grep -v ")" | grep -v "indirect" | awk '{$1=$1; print "  - [" $1 "](https://" $1 ") (" $2 ")"}')
fi

# 3. Analyze Frontend (React)
echo "⚛️ Analyzing Frontend..."
PKG_JSON="$FE_DIR/package.json"

# Helper to extract version from package.json
get_npm_version() {
    grep "\"$1\":" "$PKG_JSON" | head -n 1 | cut -d '"' -f 4
}

REACT_VER=$(get_npm_version "react")
VITE_VER=$(get_npm_version "vite")
TS_VER=$(get_npm_version "typescript")

# Detect Styling
STYLING="CSS"
if grep -q "tailwindcss" "$PKG_JSON"; then
    TAILWIND_VER=$(get_npm_version "tailwindcss")
    STYLING="Tailwind CSS ($TAILWIND_VER)"
fi

# Extract Key Dependencies (just a list of formatted strings)
# Logic: Scan for specific known libraries or list main deps
FE_DEPS_LIST=""
for lib in "lucide-react" "axios" "date-fns" "framer-motion" "clsx" "zod" "react-router-dom"; do
    ver=$(get_npm_version "$lib")
    if [ ! -z "$ver" ]; then
        FE_DEPS_LIST="${FE_DEPS_LIST}  - **$lib:** $ver\n"
    fi
done

# If empty, just grab first 5 regular dependencies
if [ -z "$FE_DEPS_LIST" ]; then
     FE_DEPS_LIST=$(grep -A 10 '"dependencies":' "$PKG_JSON" | grep -v "dependencies" | grep -v "{" | grep -v "}" | head -n 5 | awk -F: '{print "  - " $1 ": " $2}' | tr -d '",')
fi


# 4. Generate Report
echo "📝 Generating Report at $REPORT_FILE..."

cat > "$REPORT_FILE" <<EOF
# Data Generator - Tech Stack Audit Report
**Date:** $(date)
**Generated By:** check_techstack.sh

## 🐘 Backend (Go)
- **Go Version:** $GO_VERSION
- **Go Sum Integrity:** $GO_SUM_STATUS
- **Detected Dependencies:**
$GO_DEPS

## ⚛️ Frontend (React)
- **Framework:** React $REACT_VER
- **Language:** TypeScript $TS_VER
- **Build Tool:** Vite $VITE_VER
- **Styling Engine:** $STYLING
- **Key Libraries:**
$FE_DEPS_LIST

## 🛡️ Deployment Requirements
### Server (Ubuntu)
- **Service Manager:** systemd
- **Reverse Proxy:** Nginx (v1.18+)
- **SSL:** OpenSSL (Self-Signed)

### Build Environment
- **Go Compiler:** $GO_VERSION (Required for build)
- **Node.js:** v18+ (Recommended for Vite/React)

---
*Report generated automatically.*
EOF

echo "✅ Audit Complete! Check '$REPORT_FILE' for details."
