#!/bin/bash
# Quick reference commands for restarting the server

echo "╔════════════════════════════════════════════════════════╗"
echo "║         🔧 RESTART SERVER - COMMAND REFERENCE         ║"
echo "╚════════════════════════════════════════════════════════╝"
echo ""
echo "📍 Current Location: Terminal 1 (where ./bin/server is running)"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  METHOD 1: Manual Restart (Recommended)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Step 1: Stop the server"
echo "  → Press: Ctrl + C"
echo ""
echo "Step 2: Restart the server"
echo "  → Run: ./bin/server"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "  METHOD 2: Auto-Restart Script"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "Run in a new terminal:"
echo "  → cd /home/fitkhi/KERJA/DEVELOPMENT/CODEBASE/data-generator-fe-be-v1/be"
echo "  → ./restart-server.sh"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
